In [2]:
#import numpy library 
import numpy as np

# Creating Array

In [3]:
array= np.array([1,2,3,4,5])
print(array)
print("Shape:",array.shape)                #Indicates how many rows and columns the array consists of.
print("Dimension:",array.ndim)             #Returns dimension of array
print("Data Type:",array.dtype.name)       #Returns the data type of the elements in the array.
print("Size:",array.size)                  
print("Type:",type(array))

[1 2 3 4 5]
Shape: (5,)
Dimension: 1
Data Type: int32
Size: 5
Type: <class 'numpy.ndarray'>


In [4]:
array2=np.array([1,2,3,4,5,6,7,8,9])
array3=np.array([[1,2,3,4,5,6,7,8,9]])
print(array2.ndim)
print(array3.ndim)

1
2


In [5]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a= array.reshape(3,4)                  #Changes the number of rows and columns of the array.
print(a)
print("Shape:",a.shape)                
print("Dimension:",a.ndim)             
print("Data Type:",a.dtype.name)      
print("Size:",a.size)                  #Returns the size of the array before the reshape method.              
print("Type:",type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Dimension: 2
Data Type: int32
Size: 12
Type: <class 'numpy.ndarray'>


In [12]:
arr= np.arange(0,100,10)            #inclusive , exclusive,increase amount
print(arr)

[ 0 10 20 30 40 50 60 70 80 90]


In [13]:
arr2 = np.linspace(0,5,10)          #inclusive, inclusive , how many numbers 
print(arr2)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# Basic Features
Counting in arrays starts from zero.
Columns: 0   1   2
Rows: 0 {1   2   3 
      1  4   5   6
      2  7   8   9}

In [20]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[1,1])                            #1.row and 1.column
print(arr[:,1])                            #All rows and 1.column
print(arr[1,:])                            #All columns and 1.row
print(arr[-1,:])                           #Last row and and all columns
print(arr[:,-1])                           #Last column and all rows
print(arr[1,1:3])                          #1.row and 1.column-3.column

[[1 2 3 4]
 [5 6 7 8]]
6
[2 6]
[5 6 7 8]
[5 6 7 8]
[4 8]
[6 7]


In [22]:
#Difference between list and array
liste= [1,2,3,4,5,6]
array= np.array([9,8,7,6,5,4])
print(liste)
print(array)

[1, 2, 3, 4, 5, 6]
[9 8 7 6 5 4]


In [23]:
#Convert list to array
array=np.array(liste)
print(array)
#Convert array to list
liste2=list(array)
print(liste2)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [29]:
x = np.array([1,2,3,4,5,6,7,8,9])     #If an index of an array changes, all arrays change.
y = x
z = x
y[0]=10
print(x,y,z)

x = np.array([1,2,3,4,5,6,7,8,9])
w = x.copy()                         #If any index changes in the copy method, this array is not affected.
print(w)   

[10  2  3  4  5  6  7  8  9] [10  2  3  4  5  6  7  8  9] [10  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]


In [36]:
array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1= array.reshape(2,6)                                #Changes made with the reshape method are temporary.
print(arr1)
print(array)

array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])   #Changes made with the resize method are permanent.
arr2= array.resize((3,4))
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a= arr.ravel()                                        #Ravel method converts the array to one-dimensional form.
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
#Reverse of Array
x = np.array([1,2,3,4,5,6,7,8,9]) 
x_reverse= x[: : -1]
print(x_reverse)

[9 8 7 6 5 4 3 2 1]


In [41]:
#Transpose of Array
y= np.array([[1,2,3],[4,5,6],[7,8,9]])
y_transpose= y.T
print(y_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Creating Special Matrix
-Zero Matrix
-Ones Matrix
-Unit Matrix
-Empty Matrix

In [6]:
zeros=np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
ones= np.ones((2,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
unit=np.eye((5))
print(unit)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
empty_matrix= np.empty([5,3])           #Create an empty array with length 5,3
empty_matrix.fill(9)                    #The empty array is filled with the number 9.
print(empty_matrix)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


# Basic Operations
-Arithmetic Operations
-Special Functions
-Matrix Multiplication

In [14]:
x= np.array([1,2,3,4])
y= np.array([9,8,7,6])

print(x+y)
print(x-y)
print(x*y)
print(x**2)
print(y+2)

[10 10 10 10]
[-8 -6 -4 -2]
[ 9 16 21 24]
[ 1  4  9 16]
[11 10  9  8]


In [15]:
array= np.array([1,2,3,4,5,6,7,8,9])
arr= array.reshape(3,3)
print(arr)
print(arr.sum())                 #sum of all elements in array
print(arr.max())                 #find maximum element in array
print(arr.min())                 #find maximum element in array
print(arr.mean())
print(np.median(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
9
1
5.0
5.0


In [16]:
array = np.array([1,2,3,4,5,6,7,8])
x = array.reshape(4,2)
y = array.reshape(2,4)
print(np.dot(x,y))

[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]
 [47 62 77 92]]
